// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CongReports.Migrations
{
    [DbContext(typeof(CongReportsContext))]
    [Migration("20221014220751_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("Publicadores.Models.Publicador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsAnciano")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsPrecursor")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsSiervoMinisterial")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsUngido")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaBautismo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Publicador");
                });
#pragma warning restore 612, 618
        }
    }
}
