// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CongReports.Migrations.Informes
{
    [DbContext(typeof(InformesContext))]
    partial class InformesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("CongReports.Models.Informe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Estudios")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Horas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notas")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("PrecursorAuxiliar")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Publicaciones")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PublicadorId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Revisitas")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Videos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PublicadorId");

                    b.ToTable("Informe");
                });

            modelBuilder.Entity("CongReports.Models.Publicador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EsAnciano")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsPrecursor")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsSiervoMinisterial")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EsUngido")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FechaBautismo")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Publicador");
                });

            modelBuilder.Entity("CongReports.Models.Informe", b =>
                {
                    b.HasOne("CongReports.Models.Publicador", "Publicador")
                        .WithMany()
                        .HasForeignKey("PublicadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publicador");
                });
#pragma warning restore 612, 618
        }
    }
}
